#install the packages presented in pipinstall_py3.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r ./pipinstall_py3.txt

# Set up our notebook config.
COPY python3_config.py /root/.jupyter/

WORKDIR /bphy170

CMD ["/run_jupyter.sh", "--allow-root"] 
# When running this Docker image, /run_jupyter.sh will be run, starting up a Jupyter link
